# Generated by Django 3.1.3 on 2021-09-28 08:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210928_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='created_on',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='quantity_unit',
            field=models.CharField(blank=True, choices=[('none', ''), ('kg', 'Kg'), ('ltr', 'L'), ('nos', 'Nos')], default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='item',
            name='updated_on',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
